<?xml version="1.0"?>
<SavedData xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <PlayerPosition>
    <X>2</X>
    <Y>1.49992228</Y>
    <Z>-20.6189442</Z>
  </PlayerPosition>
  <PlayerScore>7</PlayerScore>
  <PlayerScoreMax>549</PlayerScoreMax>
  <KeysList />
  <CoinList>
    <CoinSerializable>
      <CoinPosition>
        <X>31</X>
        <Y>0.5</Y>
        <Z>9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>-6.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>7.6</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>-6.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>0.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>41</X>
        <Y>0.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>0.5</Y>
        <Z>-14</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>-1</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>29</X>
        <Y>0.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>0.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>7.6</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>0.5</Y>
        <Z>-17</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>26</X>
        <Y>-6.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>0.5</Y>
        <Z>-23</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-20</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-25</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>7.6</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>-6.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>-6.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>-6.5</Y>
        <Z>-10</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-21</X>
        <Y>0.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-21</X>
        <Y>-6.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>0.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>19</X>
        <Y>0.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>0.5</Y>
        <Z>6</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21.88</X>
        <Y>0.5</Y>
        <Z>-3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>-6.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>37</X>
        <Y>0.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>-6.5</Y>
        <Z>-42</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>10</X>
        <Y>-6.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>-6.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>31</X>
        <Y>7.6</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>28</X>
        <Y>-6.5</Y>
        <Z>9</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>0.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>0.5</Y>
        <Z>9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>-6.5</Y>
        <Z>-15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>0.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>13</X>
        <Y>0.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>0.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>-6.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-35</X>
        <Y>7.6</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>0.5</Y>
        <Z>13</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>-6.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>-6.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>0.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>10</X>
        <Y>7.6</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>0.5</Y>
        <Z>23</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>0.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-20</X>
        <Y>7.6</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>-6.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>-6.5</Y>
        <Z>-5</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>0.5</Y>
        <Z>-11</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>0.5</Y>
        <Z>-19</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-13</X>
        <Y>0.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>-6.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>15</X>
        <Y>-6.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>-6.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-35</X>
        <Y>-6.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>30</X>
        <Y>7.6</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-30</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>0.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-25</X>
        <Y>7.6</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>-6.5</Y>
        <Z>-25</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>0.5</Y>
        <Z>-37</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>0.5</Y>
        <Z>-31</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>0.5</Y>
        <Z>11</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>-6.5</Y>
        <Z>-15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>38</X>
        <Y>-6.5</Y>
        <Z>-2</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>0.5</Y>
        <Z>-17</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>0.5</Y>
        <Z>-5</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>0.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>-6.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>13</X>
        <Y>0.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>7.6</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>29</X>
        <Y>0.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>-40</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>-6.5</Y>
        <Z>-30</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>8</X>
        <Y>-6.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>0.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>0.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>35</X>
        <Y>7.6</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-21</X>
        <Y>7.6</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>-6.5</Y>
        <Z>-3</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-35</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>0.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-21</X>
        <Y>-6.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>7.6</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-40</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>25</X>
        <Y>7.6</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>-6.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-30</X>
        <Y>-6.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>0.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>0.5</Y>
        <Z>17</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>0.5</Y>
        <Z>16</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>-6.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>11</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>20</X>
        <Y>-6.5</Y>
        <Z>4</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-10</X>
        <Y>-6.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>0.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-35</X>
        <Y>0.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-21</X>
        <Y>0.5</Y>
        <Z>-3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-7</X>
        <Y>0.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-20</X>
        <Y>-6.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>40</X>
        <Y>7.6</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-23</X>
        <Y>0.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>14</X>
        <Y>-6.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>-6.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>-6.5</Y>
        <Z>0</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>15</X>
        <Y>-6.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>0.5</Y>
        <Z>1</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>15</X>
        <Y>-6.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>0.5</Y>
        <Z>-41</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>0.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>-6.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>14</X>
        <Y>-6.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-10</X>
        <Y>-6.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>25</X>
        <Y>-6.5</Y>
        <Z>4</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>-6.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-5</X>
        <Y>-6.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>0.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>0</X>
        <Y>-6.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>0.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-21</X>
        <Y>0.5</Y>
        <Z>9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>0.5</Y>
        <Z>-13</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>37</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>0.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>0.5</Y>
        <Z>13</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>5</X>
        <Y>-6.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>0.5</Y>
        <Z>-1</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>-6.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>0.5</Y>
        <Z>8.24</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>-6.5</Y>
        <Z>-40</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>-6.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>-6.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>-6.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>-6.5</Y>
        <Z>5</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>-6.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>37</X>
        <Y>-6.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>40</X>
        <Y>-6.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-7</X>
        <Y>0.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-40</X>
        <Y>-6.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>0.5</Y>
        <Z>-7</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>0.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>0.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>-6.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>0.5</Y>
        <Z>-15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>7</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>-6.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>0.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>-6.5</Y>
        <Z>10</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>7.6</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>0.5</Y>
        <Z>5</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>0.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>0.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>0.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-23</X>
        <Y>0.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>26</X>
        <Y>7.6</Y>
        <Z>39.07</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-40</X>
        <Y>-6.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>-6.5</Y>
        <Z>5</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>18</X>
        <Y>-6.5</Y>
        <Z>9</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>0.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>-6.5</Y>
        <Z>5</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-10</X>
        <Y>-6.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>0.5</Y>
        <Z>-3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>0.5</Y>
        <Z>-28</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>-6.5</Y>
        <Z>-15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>43</X>
        <Y>-6.5</Y>
        <Z>-22</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>-6.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>35</X>
        <Y>0.5</Y>
        <Z>9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>-6.5</Y>
        <Z>-29.75</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>0.5</Y>
        <Z>1</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>0.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-30</X>
        <Y>-6.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>0.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>43</X>
        <Y>-6.5</Y>
        <Z>9</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>16</X>
        <Y>0.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>-6.5</Y>
        <Z>-35</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>38</X>
        <Y>-6.5</Y>
        <Z>-42</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>-6.5</Y>
        <Z>9</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>-6.5</Y>
        <Z>0</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>-6.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>0.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>7.6</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>-6.5</Y>
        <Z>-15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>0.5</Y>
        <Z>-3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>35</X>
        <Y>7.6</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>-6.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>-29</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>-6.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>20</X>
        <Y>7.6</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>0.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>0.5</Y>
        <Z>-23</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>-6.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-5</X>
        <Y>-6.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>43</X>
        <Y>-6.5</Y>
        <Z>-37</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>5</X>
        <Y>-6.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>0.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>0.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>-6.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-10</X>
        <Y>-6.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>0.5</Y>
        <Z>-17</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-34</X>
        <Y>0.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-21</X>
        <Y>-6.5</Y>
        <Z>-15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-11</X>
        <Y>0.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>31</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>-6.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>0.5</Y>
        <Z>-15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>0.5</Y>
        <Z>-17</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>41</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>-6.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-40</X>
        <Y>-6.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-7</X>
        <Y>0.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>0.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>0.5</Y>
        <Z>1</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>0.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>0.5</Y>
        <Z>-31</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>-6.5</Y>
        <Z>-15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>0.5</Y>
        <Z>-15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>-6.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>25.68</X>
        <Y>0.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>0.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>-6.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>0.5</Y>
        <Z>-1</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>0.5</Y>
        <Z>-23</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>0.5</Y>
        <Z>-35</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>0.5</Y>
        <Z>-29</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>-6.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-20</X>
        <Y>-6.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>25</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>0.5</Y>
        <Z>-3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-10</X>
        <Y>-6.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>-6.5</Y>
        <Z>-3</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>5</X>
        <Y>-6.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-20</X>
        <Y>-6.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>7.6</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>0.5</Y>
        <Z>11</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>43</X>
        <Y>-6.5</Y>
        <Z>-7</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>-6.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>17</X>
        <Y>0.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-25</X>
        <Y>-6.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>7.6</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>0.5</Y>
        <Z>-25</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-21</X>
        <Y>-6.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>0.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>0.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>5</X>
        <Y>7.6</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>-5</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>17</X>
        <Y>0.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>-6.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>46</X>
        <Y>7.6</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>-6.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-20</X>
        <Y>-6.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>2</X>
        <Y>-6.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>0.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>0.5</Y>
        <Z>-13</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>41</X>
        <Y>7.6</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-1</X>
        <Y>0.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>15</X>
        <Y>0.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>10</X>
        <Y>-6.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-21</X>
        <Y>0.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>7.6</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>0.5</Y>
        <Z>-3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>-6.5</Y>
        <Z>-3</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>23</X>
        <Y>0.5</Y>
        <Z>-15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>7.6</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>0.5</Y>
        <Z>19</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>7.6</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>-6.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>-6.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>0.5</Y>
        <Z>5</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>-6.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>0.5</Y>
        <Z>-17</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>-6.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>0.5</Y>
        <Z>-11</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>0.5</Y>
        <Z>-13</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>0.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>0.5</Y>
        <Z>13</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>7.6</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>38</X>
        <Y>-6.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>-6.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>-6.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>0.5</Y>
        <Z>11</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>0.5</Y>
        <Z>-37</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-21</X>
        <Y>7.6</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>5</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33.68</X>
        <Y>0.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-25</X>
        <Y>-6.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>7.6</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>43</X>
        <Y>-6.5</Y>
        <Z>-32</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>38</X>
        <Y>-6.5</Y>
        <Z>9</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>29</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>-6.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>0.5</Y>
        <Z>17</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>0.5</Y>
        <Z>9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>0.5</Y>
        <Z>-5</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>-6.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>-6.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>43</X>
        <Y>-6.5</Y>
        <Z>-2</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>0.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>31</X>
        <Y>7.6</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>-6.5</Y>
        <Z>-34.5</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>0.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>23</X>
        <Y>-6.5</Y>
        <Z>9</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-35</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>0.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>0.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>-6.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>11</X>
        <Y>0.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-21</X>
        <Y>-6.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>0.5</Y>
        <Z>11</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>7.6</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>-6.5</Y>
        <Z>-42</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>0.5</Y>
        <Z>9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>15</X>
        <Y>7.6</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>20</X>
        <Y>-6.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>0</X>
        <Y>0.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>0.5</Y>
        <Z>-1</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-5</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>-6.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>-6.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>7.6</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-30</X>
        <Y>7.6</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>-6.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-25</X>
        <Y>-6.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>41</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>0.5</Y>
        <Z>-13</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>0.5</Y>
        <Z>-15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>10</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>-6.5</Y>
        <Z>9</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>-6.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-29</X>
        <Y>0.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>-25</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>43</X>
        <Y>-6.5</Y>
        <Z>3.5</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>0.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>-6.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-14</X>
        <Y>0.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-24</X>
        <Y>0.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>0</X>
        <Y>-6.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>0.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-30</X>
        <Y>-6.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>13</X>
        <Y>0.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>0.5</Y>
        <Z>-13</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>42</X>
        <Y>-6.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>25</X>
        <Y>0.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-35</X>
        <Y>-6.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-26</X>
        <Y>0.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>0.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>-6.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>-6.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>0.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>18</X>
        <Y>-6.5</Y>
        <Z>-3</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>29.68</X>
        <Y>0.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>0.5</Y>
        <Z>-7</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-31</X>
        <Y>0.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>0.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>0</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>23</X>
        <Y>0.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-21</X>
        <Y>0.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>29</X>
        <Y>0.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>-6.5</Y>
        <Z>13</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>-6.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>-6.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>7.6</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-40</X>
        <Y>7.6</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>0.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>0.5</Y>
        <Z>-5</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>36</X>
        <Y>7.6</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-40</X>
        <Y>-6.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>7.6</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>7.6</Y>
        <Z>19</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>0.5</Y>
        <Z>-11</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>19</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>-6.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>-6.5</Y>
        <Z>9</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>0.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>0.5</Y>
        <Z>-5</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-35</X>
        <Y>-6.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>0.5</Y>
        <Z>-25</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>32</X>
        <Y>-6.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>0.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>0.5</Y>
        <Z>-37</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>0.5</Y>
        <Z>-4</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-35</X>
        <Y>-6.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>17.88</X>
        <Y>0.5</Y>
        <Z>-3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-7</X>
        <Y>0.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>0.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>7.6</Y>
        <Z>23</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>0.5</Y>
        <Z>-29</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-5</X>
        <Y>-6.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>0.5</Y>
        <Z>-19</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>7.6</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>0.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>-6.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-29</X>
        <Y>-6.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>-6.5</Y>
        <Z>-15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>0.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>7.6</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>0.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-17</X>
        <Y>0.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>-6.5</Y>
        <Z>-15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-21</X>
        <Y>0.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>0.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>25</X>
        <Y>0.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>7.6</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>0.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>7.6</Y>
        <Z>-1</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-19.5</X>
        <Y>-6.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-10</X>
        <Y>-6.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>0.5</Y>
        <Z>-17</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>-6.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>7.6</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-5</X>
        <Y>7.6</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>0.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>25</X>
        <Y>0.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>-6.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>0.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>-6.5</Y>
        <Z>-2</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>0.5</Y>
        <Z>12.24</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>13</X>
        <Y>0.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>7.6</Y>
        <Z>-3</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-30</X>
        <Y>-6.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>0.5</Y>
        <Z>9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>13</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>-6.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>0.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>17</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>17</X>
        <Y>0.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-20.5</X>
        <Y>0.5</Y>
        <Z>-15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>0.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-20</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>0.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-19</X>
        <Y>0.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>0.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-11</X>
        <Y>0.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>0.5</Y>
        <Z>9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>0.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>-6.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-21</X>
        <Y>0.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>43</X>
        <Y>-6.5</Y>
        <Z>-42</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>-6.5</Y>
        <Z>-20</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>21</X>
        <Y>0.5</Y>
        <Z>16.24</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>15</X>
        <Y>-6.5</Y>
        <Z>4</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-10</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>-6.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>-6.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-40</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-20</X>
        <Y>-6.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>-6.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>-17</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>29</X>
        <Y>0.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>19</X>
        <Y>0.5</Y>
        <Z>-15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>-6.5</Y>
        <Z>-25</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>15</X>
        <Y>7.6</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-21</X>
        <Y>0.5</Y>
        <Z>15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>7.6</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>25</X>
        <Y>0.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>43</X>
        <Y>-6.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-33</X>
        <Y>-6.5</Y>
        <Z>9</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>46</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>0.5</Y>
        <Z>-29</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>-6.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-11</X>
        <Y>0.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>0.5</Y>
        <Z>11</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>0.5</Y>
        <Z>-29</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-19</X>
        <Y>0.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>0.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>43</X>
        <Y>-6.5</Y>
        <Z>-17</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>-13</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>17</X>
        <Y>0.5</Y>
        <Z>-21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>0.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>0.5</Y>
        <Z>-7</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>33</X>
        <Y>0.5</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>0.5</Y>
        <Z>-13</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>0.5</Y>
        <Z>-1</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>15</X>
        <Y>7.6</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>-6.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>0.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-25</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-25</X>
        <Y>-6.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>0.5</Y>
        <Z>-27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-10</X>
        <Y>7.6</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>-6.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>43</X>
        <Y>-6.5</Y>
        <Z>-12</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-21</X>
        <Y>-6.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>15</X>
        <Y>-6.5</Y>
        <Z>25</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>15</X>
        <Y>-6.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>0.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>-6.5</Y>
        <Z>-20</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>0.5</Y>
        <Z>7</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>0.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>35</X>
        <Y>0.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>3</X>
        <Y>-6.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>27</X>
        <Y>-6.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>0.5</Y>
        <Z>-9</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>13.8799992</X>
        <Y>0.5</Y>
        <Z>-3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>0.5</Y>
        <Z>-25</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>7.6</Y>
        <Z>-5</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>-6.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-15</X>
        <Y>-6.5</Y>
        <Z>-15</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>0.5</Y>
        <Z>7</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-30</X>
        <Y>0.5</Y>
        <Z>-45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>0.5</Y>
        <Z>-1</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>36</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>0</X>
        <Y>7.6</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>0.5</Y>
        <Z>3</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>0.5</Y>
        <Z>-1</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>5</X>
        <Y>0.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>0.5</Y>
        <Z>11</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-27</X>
        <Y>0.5</Y>
        <Z>1</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>-6.5</Y>
        <Z>21</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>0.5</Y>
        <Z>7</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-39</X>
        <Y>0.5</Y>
        <Z>45</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-3</X>
        <Y>7.6</Y>
        <Z>7</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-11</X>
        <Y>0.5</Y>
        <Z>33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>39</X>
        <Y>0.5</Y>
        <Z>5</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-14.5</X>
        <Y>0.5</Y>
        <Z>-15</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>25</X>
        <Y>0.5</Y>
        <Z>27</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-21</X>
        <Y>0.5</Y>
        <Z>-33</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>0.5</Y>
        <Z>23</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>31</X>
        <Y>0.5</Y>
        <Z>-39</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-9</X>
        <Y>0.5</Y>
        <Z>-35</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>-45</X>
        <Y>-6.5</Y>
        <Z>10</Z>
      </CoinPosition>
      <CoinFloor>0</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>45</X>
        <Y>0.5</Y>
        <Z>-25</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>15</X>
        <Y>7.6</Y>
        <Z>39</Z>
      </CoinPosition>
      <CoinFloor>2</CoinFloor>
    </CoinSerializable>
    <CoinSerializable>
      <CoinPosition>
        <X>9</X>
        <Y>0.5</Y>
        <Z>17</Z>
      </CoinPosition>
      <CoinFloor>1</CoinFloor>
    </CoinSerializable>
  </CoinList>
</SavedData>